// Code generated by entc, DO NOT EDIT.

package app

import (
	"time"
)

const (
	// Label holds the string label denoting the app type in the database.
	Label = "app"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBundleID holds the string denoting the bundle_id field in the database.
	FieldBundleID = "bundle_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldLogo holds the string denoting the logo field in the database.
	FieldLogo = "logo"
	// FieldLatestVersion holds the string denoting the latest_version field in the database.
	FieldLatestVersion = "latest_version"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeVersions holds the string denoting the versions edge name in mutations.
	EdgeVersions = "versions"
	// Table holds the table name of the app in the database.
	Table = "apps"
	// UserTable is the table that holds the user relation/edge. The primary key declared below.
	UserTable = "user_apps"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// VersionsTable is the table that holds the versions relation/edge. The primary key declared below.
	VersionsTable = "app_versions"
	// VersionsInverseTable is the table name for the Version entity.
	// It exists in this package in order to avoid circular dependency with the "version" package.
	VersionsInverseTable = "versions"
)

// Columns holds all SQL columns for app fields.
var Columns = []string{
	FieldID,
	FieldBundleID,
	FieldName,
	FieldLogo,
	FieldLatestVersion,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// UserPrimaryKey and UserColumn2 are the table columns denoting the
	// primary key for the user relation (M2M).
	UserPrimaryKey = []string{"user_id", "app_id"}
	// VersionsPrimaryKey and VersionsColumn2 are the table columns denoting the
	// primary key for the versions relation (M2M).
	VersionsPrimaryKey = []string{"app_id", "version_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updatedAt" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updatedAt" field.
	UpdateDefaultUpdatedAt func() time.Time
)
