// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"
	"yayar/internal/data/ent/app"
	"yayar/internal/data/ent/history"
	"yayar/internal/data/ent/schema"
	"yayar/internal/data/ent/user"
	"yayar/internal/data/ent/version"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appFields := schema.App{}.Fields()
	_ = appFields
	// appDescCreatedAt is the schema descriptor for createdAt field.
	appDescCreatedAt := appFields[4].Descriptor()
	// app.DefaultCreatedAt holds the default value on creation for the createdAt field.
	app.DefaultCreatedAt = appDescCreatedAt.Default.(func() time.Time)
	// appDescUpdatedAt is the schema descriptor for updatedAt field.
	appDescUpdatedAt := appFields[5].Descriptor()
	// app.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	app.DefaultUpdatedAt = appDescUpdatedAt.Default.(func() time.Time)
	// app.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	app.UpdateDefaultUpdatedAt = appDescUpdatedAt.UpdateDefault.(func() time.Time)
	historyFields := schema.History{}.Fields()
	_ = historyFields
	// historyDescCreatedAt is the schema descriptor for createdAt field.
	historyDescCreatedAt := historyFields[2].Descriptor()
	// history.DefaultCreatedAt holds the default value on creation for the createdAt field.
	history.DefaultCreatedAt = historyDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for createdAt field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the createdAt field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updatedAt field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	versionFields := schema.Version{}.Fields()
	_ = versionFields
	// versionDescApkSize is the schema descriptor for apk_size field.
	versionDescApkSize := versionFields[2].Descriptor()
	// version.DefaultApkSize holds the default value on creation for the apk_size field.
	version.DefaultApkSize = versionDescApkSize.Default.(float64)
	// versionDescIpaSize is the schema descriptor for ipa_size field.
	versionDescIpaSize := versionFields[3].Descriptor()
	// version.DefaultIpaSize holds the default value on creation for the ipa_size field.
	version.DefaultIpaSize = versionDescIpaSize.Default.(float64)
	// versionDescIpaURL is the schema descriptor for ipa_url field.
	versionDescIpaURL := versionFields[4].Descriptor()
	// version.DefaultIpaURL holds the default value on creation for the ipa_url field.
	version.DefaultIpaURL = versionDescIpaURL.Default.(string)
	// versionDescApkURL is the schema descriptor for apk_url field.
	versionDescApkURL := versionFields[5].Descriptor()
	// version.DefaultApkURL holds the default value on creation for the apk_url field.
	version.DefaultApkURL = versionDescApkURL.Default.(string)
	// versionDescPlistURL is the schema descriptor for plist_url field.
	versionDescPlistURL := versionFields[6].Descriptor()
	// version.DefaultPlistURL holds the default value on creation for the plist_url field.
	version.DefaultPlistURL = versionDescPlistURL.Default.(string)
	// versionDescDescription is the schema descriptor for description field.
	versionDescDescription := versionFields[7].Descriptor()
	// version.DefaultDescription holds the default value on creation for the description field.
	version.DefaultDescription = versionDescDescription.Default.(string)
	// versionDescAccess is the schema descriptor for access field.
	versionDescAccess := versionFields[8].Descriptor()
	// version.DefaultAccess holds the default value on creation for the access field.
	version.DefaultAccess = versionDescAccess.Default.(string)
	// versionDescAccessCode is the schema descriptor for access_code field.
	versionDescAccessCode := versionFields[9].Descriptor()
	// version.DefaultAccessCode holds the default value on creation for the access_code field.
	version.DefaultAccessCode = versionDescAccessCode.Default.(string)
	// versionDescStatus is the schema descriptor for status field.
	versionDescStatus := versionFields[10].Descriptor()
	// version.DefaultStatus holds the default value on creation for the status field.
	version.DefaultStatus = versionDescStatus.Default.(int)
	// versionDescCreatedAt is the schema descriptor for createdAt field.
	versionDescCreatedAt := versionFields[11].Descriptor()
	// version.DefaultCreatedAt holds the default value on creation for the createdAt field.
	version.DefaultCreatedAt = versionDescCreatedAt.Default.(func() time.Time)
	// versionDescUpdatedAt is the schema descriptor for updatedAt field.
	versionDescUpdatedAt := versionFields[12].Descriptor()
	// version.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	version.DefaultUpdatedAt = versionDescUpdatedAt.Default.(func() time.Time)
	// version.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	version.UpdateDefaultUpdatedAt = versionDescUpdatedAt.UpdateDefault.(func() time.Time)
}
