// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// App is the predicate function for app builders.
type App func(*sql.Selector)

// History is the predicate function for history builders.
type History func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Version is the predicate function for version builders.
type Version func(*sql.Selector)
